# TMUX — Multiplexor. QUÉ EDITAR: prefix, splits, plugins
# Plugins: instalar tpm primero: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB,kitty:Tc"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g set-clipboard on
set -g escape-time 0
set -g history-limit 50000

# Prefix: Ctrl+a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Splits
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Navegación vim-like
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

run '~/.tmux/plugins/tpm/tpm'
